### ISSUE TITLE
vocoder model missing? 

### ISSUE THREAD

**Issue by akoepke** [XYPB/CondFoleyGen#10]
Hi, 

Thanks for sharing code for your work!  

I tried to run the ‘quick demo’ that you mentioned in your README:

```
mkdir logs
python audio_generation.py --gh_demo --model_name 2022-05-03T11-33-05_greatesthit_transformer_with_vNet_randshift_2s_GH_vqgan_no_earlystop --target_log_dir demo_output --W_scale 3
```

However, I get this error:

`FileNotFoundError: [Errno 2] No such file or directory: 'vocoder/logs/vggsound/best_netG.pt'`

Would it be possible to provide the vocoder model, too? 

Many thanks!

**Comment by XYPB** [comment]
Hi,


Thanks for your comment. In fact, we used the same vocoder MelGAN model as SpecVQGAN, and you can find the URL to download this netG via: https://github.com/v-iashin/SpecVQGAN#vggish-ish-melception-and-melgan
Hope this can solve your question.

Best,
Yuexi

**Comment by akoepke** [comment]
Thank you for the prompt reply!

Would you be able to add the demo video which according to the demo should be located in

`data/demo_video/hitting_metal.mp4`

Thank you!

**Comment by XYPB** [comment]
I apologize for this. I forgot to add the demo video when releasing the model. You should now be able to find it under the `data/demo_video` folder.
