### ISSUE TITLE
When to release the pretrained model?

### ISSUE THREAD

**Issue by yzxing87** [XYPB/CondFoleyGen#2]
Awesome work! May I know when do you plan to release the pretrained weights?

**Comment by XYPB** [comment]
Thanks for your attention! We plan to release the pre-trained weights, but one concern is that one was trained with a slightly different setting (processed spectrogram instead of waveform), so we need some extra time to adapt to the current release. But it should be released soon this month.

**Comment by riccardofosco95** [comment]
Hey, thank you for your amazing work! Any update for the pretrained models release?

**Comment by XYPB** [comment]
We have just uploaded the pre-trained models for both datasets, please feel free to check out!
