### ISSUE TITLE
Error when trying to train VQ-GAN codebook model

### ISSUE THREAD

**Issue by mcomunita** [XYPB/CondFoleyGen#3]
Hi!

First of all, thank you very much for the amazing work and the code.

I am trying to train the VQ-GAN codebook model following your instructions from Step 1.

Although, if I run
`python train.py --base configs/greatesthit_codebook.yaml -t True --gpus 0,`

I get the following error:
`FileNotFoundError:` [Errno 2] No such file or directory: 'vocoder/logs/vggsound/best_netG.pt'`

What model is it referring to?

Thanks

**Comment by XYPB** [comment]
Thank you for the issue. This refers to the MelGAN checkpoints that will be used to generate waveform from the spectrogram. 

Though we will provide them later when we release the full checkpoint. You can also find these files from [here](https://github.com/v-iashin/SpecVQGAN#vggish-ish-melception-and-melgan), which is pre-trained by Iashin et.al. We used the same MelGAN in our projects. and you can place them according to the error information.

We will also update the README for this issue.

Thank you!

**Comment by mcomunita** [comment]
Thanks a lot for the quick answer
