### ISSUE TITLE
video_onset_net

### ISSUE THREAD

**Issue by Yusiissy** [XYPB/CondFoleyGen#8]
Hello! I came across your paper and noticed the Onset Transfer method you introduced for audio. I found your approach of training the video_onset_net to recognize onsets in a silent video quite intriguing. I'm very interested in diving deeper into this methodology. While exploring your repository, I came across the CondFoleyGen/predict_onset.py script.

Could you kindly inform me if you have any intentions of making the checkpoint (ckpt) file for this network available? I'd greatly appreciate it if there's a possibility of obtaining the ckpt file to experiment with the model.

Furthermore, I'm interested in the training process for this network. Could you provide some guidance or documentation on how to train the video_onset_net? Any insights or pointers you can provide would be extremely helpful.

Thank you for your time and consideration! Looking forward to learning more about your research and methods.

**Comment by XYPB** [comment]
Thank you so much for your interest!

We have just updated the README file and you can now see more details about the train&test&generation of the onset transfer baseline! This should include all the information needed to reproduce the onset baseline we proposed in the paper.

As the checkpoints for these onset baseline models, I am afraid I cannot release them before I return to the US at the end of August (as mentioned in issue  #2 ). But considering that the training of this baseline is reasonably straightforward, you may train it yourself if you want.

Additionally, the `predict_onset.py` was used for video evaluation, and it does not require the onset transfer baseline model. It uses the `librosa` library to predict the onset of the generated audio for later evaluation.

Hope this can help with your questions.
